const pathMappings = {
  story: { displayName: 'Thể loại', routeTo: '/find-story' },
  'girl-story': { displayName: 'Con gái' },
  'boy-story': { displayName: 'Con trai' },
  history: { displayName: 'Lịch sử' },
  'find-story': { displayName: 'Thể loại' },
  'find-advanced': { displayName: 'Tìm truyện nâng cao' },
  following: { displayName: 'Theo dõi' },
  login: { displayName: 'Đăng nhập' },
  register: { displayName: 'Đăng ký' },
  hot: { displayName: 'Hot' },
  secure: { displayName: 'Tài khoản' },
  dashboard: { displayName: 'Thông tin chung' },
  userProfile: { displayName: 'Thông tin tài khoản' },
  comicFollowed: { displayName: 'Truyện theo dõi' },
  userPoint: { displayName: 'Linh thạch' },
  shop: { displayName: 'Cửa hàng' },
  comment: { displayName: 'Bình luận' },
  notifications: { displayName: 'Thông báo' },
  changePassword: { displayName: 'Đổi mật khẩu' },
  'forgot-password': { displayName: 'Quên mật khẩu' },
  'reset-password': { displayName: 'Đổi mật khẩu' },
  'chuyen-sinh': { displayName: 'Chuyển sinh' },
  'co-dai': { displayName: 'Cổ đại' },
  'live-action': { displayName: 'Live action' },
  'school-life': { displayName: 'School Life' },
  'thieu-nhi': { displayName: 'Thiếu nhi' },
  'trinh-tham': { displayName: 'Trinh thám' },
  'truyen-scan': { displayName: 'Truyện scan' },
  'truyen-mau': { displayName: 'Truyện màu' },
  user: { displayName: 'Thông tin thành viên' },
};
export default pathMappings;
